### ISSUE TITLE
Bad Sync on NTSC games

### ISSUE THREAD

**Issue by ZXPortugal** [jago85/UltraPIF_Hardware#3]
Hi! I own a Jap RGB capable N64, whitch i have a bortis RGB amp installed. Before the Ultra Pif was installed, everything was working ok.
Now with the Ultra Pif i have the following issues:

Menu boots fine with PAL settings and all is ok, PAL games works like charm.
When select NTSC for the menu or NTSC game, i cant get sync.

![IMG_20220104_224614](https://user-images.githubusercontent.com/95077634/148138908-07bea217-7f6f-4c5d-887a-087a5751d0d6.jpg)
![IMG_20220104_224623](https://user-images.githubusercontent.com/95077634/148138912-f1d3d8b9-7816-45ac-9941-3f342966387c.jpg)
![IMG_20220104_224628](https://user-images.githubusercontent.com/95077634/148138918-c32911bf-8b53-408f-83d5-a2a996e9ba43.jpg)
![IMG_20220104_224636](https://user-images.githubusercontent.com/95077634/148138920-5860d333-8985-4428-adb4-8cab34c6f6f5.jpg)
![IMG_20220104_224638](https://user-images.githubusercontent.com/95077634/148138924-d7f4c386-a50b-4d43-97b7-dcb1f183cdc3.jpg)

Thanks.

**Comment by jago85** [comment]
I think your FSEL signal is somehow tied to GND. Can you check this? The problem might be in one of the connectors as this signal goes between two GND connections.

**Comment by ZXPortugal** [comment]
Hi. I have checked and have 2 readings.

I have tested the FSEL to see if gives me GND signal.
With the Ultra Pif removed, i have no ground signal betwen FSEL and GND (used the pin 2 of the MX8330) but with the interface mounted i have a small reading on the multímeter continuity between FSEL and GND

Thanks in advance

Obter Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jago85** [comment]
So, it looks as there is a short on the Interface board. You can verify this by removing the board and then measure continuity from U1 pin 6 to GND.
![2022-01-05 22_14_19-3D-Betrachter](https://user-images.githubusercontent.com/36265164/148292422-f16b74cb-2739-4099-9c64-ea9d1347f95b.png)

Maybe there is a solder bridge here:
![2022-01-05 22_24_36-3D-Betrachter](https://user-images.githubusercontent.com/36265164/148292417-b76bf0e1-ac80-4994-9bea-663aa500496d.png)

I think you have 3 options:

1. Find and remove the short by yourself
2. Ask your seller for a replacement
3. Use the alternative (not yet documented) installation method that does not require FSEL.
   - close JP1 on the Interface
   - directly connect XTAL to VCLK
      - Lift and isolate pin 1 of the MX8330
      - Then connect XTAL to the VCLK pad on the motherboard
      - Pin 1 stays unconnected

**Comment by ZXPortugal** [comment]
Hi!

Have have checked for any bridges and found none. 
So i tested the alternative method.

Shorted JP1, lifted PIN 1 of the mx8330, solder the Wire from XTAL to VCLK of NUS IC, and have sucess!!

Now NTSC is working and PAL! Thanks

![IMG_20220106_152553](https://user-images.githubusercontent.com/95077634/148411654-5c2f0455-3569-4177-8e51-c0ff94638005.jpg)
![Uploading IMG_20220106_155955.jpg…]()

**Comment by jago85** [comment]
Hi! 
Great news! I still wonder why FSEL doesn't work. If it's not a short, maybe there's a problem with the contact or a dead pin. Anyway, I'm glad it's working now.
