### ISSUE TITLE
Interaction with Everdrive X7 (UltraCIC-III) and booting PAL ROMs

### ISSUE THREAD

**Issue by crozone** [jago85/UltraPIF_Hardware#5]
I am looking to install the UltraPIF into a PAL N64 to make it multi-region. The system will see use with an Everdrive X7.

I'm hoping just to clarify the behaviour of the UltraPIF in certain scenarios when used with the Everdrive X7 or similar flash cart. It's a bit complicated because the Everdrive does region detection at boot, but it can also launch any region of game after it has started up. I'm especially wondering what the behaviour will be if I launch a PAL game from an Everdrive X7 (UltraCIC-III) on a UltraPIF modded system.

Here are my current assumptions, I'm hoping if you could offer some guidance on whether they are correct or not:

### 1: UltraCIC-III will always choose NTSC on UltraPIF

My rudimentary understanding of the UltraCIC-III is that it achieves automatic region detection by first attempting to boot into NTSC mode, and if that fails, it switches over to PAL mode and reboots.

I *think* this is the UltraCIC-III code that is running in the Everdrive, and it has NTSC mode set as the initial region:

https://github.com/ManCloud/UltraCIC-III/blob/16fd1eecd8528ab2d7fd0490f24fb7738017bd39/UltraCIC-III.asm#L1038

So it looks like it'll always boot into NTSC mode when used with UltraPIF?

### 2: UltraPIF uses the CIC check to set frequencies

This one I'm not really sure about from looking at the project, but does the UltraPIF use the CIC check to set the NTSC/PAL mode (FSEL and clock, etc)? Or does it choose the mode based on the actual game behavior?

### 3: Booting PAL games

The Everdrive X7 is capable of booting PAL games on an NTSC console, and vice versa, through some magic that the Everdrive firmware does. On an un-modded N64 this leads to some weird video output because the frequencies are slightly off and the video encoder chip is still set to the console's region. I believe this causes PAL on NTSC to output as NTSC50, and NTSC on PAL to output as PAL60, and TVs don't always deal with this very well.

My assumption is that the UltraPIF won't/can't know that the Everdrive is actually booting a PAL game from NTSC mode, and will therefore always stay in NTSC mode. This will lead to PAL games booted from the Everdrive to behave as if they're running on an un-modded NTSC system, with the weird video output. Am I correct on this, or does the UltraPIF derive the region via some other method?

Thank you for any assistance you can offer.

**Comment by jago85** [comment]
Hi, 

the UltraPIF doesn't care about the CIC . You don't even need to have a CIC installed. 

The region is setup in the UltraPIF menu everytime before booting a ROM. The UltraPIF determines the region based on the country code in the ROM header to make a pre-selection of the correct region. If I remember correctly, the Everdrive has an empty country code. In this case the UltraPIF can eighter use a fixed region or remember the last region.

It's correct, that the UltraPIF doesn't know when the ED switches the region. So, if you want to play PAL games you have to start the ED in PAL mode (selected in the UltraPIF menu).

The ED could send commands to the UltraPIF and actively reset into the other region, but this is not implemented at the moment. 

Ok, I hope this short response answers your question. Feel free to ask more if it is unclear.

**Comment by crozone** [comment]
Thanks! I wasn't aware that the UltraPIF implemented its own menu at boot. I finally found a video of it in action [here](https://youtu.be/k5jYbVk9AjA?t=961), and it all makes sense now.

> It's correct, that the UltraPIF doesn't know when the ED switches the region. So, if you want to play PAL games you have to start the ED in PAL mode (selected in the UltraPIF menu).

That's exactly what I was wondering, cheers. Looks like an UltraPIF will work pretty well with an ED, it's easy to change the region just at boot. Thanks again!
