### ISSUE TITLE
Reset Ultrapif settings

### ISSUE THREAD

**Issue by Parodius79** [jago85/UltraPIF_Hardware#8]
How can you reset the ULTRAPIF settings? Upon boot I toggled the 'direct boot to cart' option in the settings, but I do not know how to undo this option or get back to the settings menu afterwards to make any further changes. 

Grateful for assistance as I am unable to find any user information online.

**Comment by jago85** [comment]
Hi,
you can return to the menu by holding down the reset button for two seconds while the game is running. (Release the button after the RGB LED starts to flash.) 

Also, you can get into the menu by booting the N64 without a cartridge.

Hope this helps :)

**Comment by Parodius79** [comment]
Yes, that works - thanks!
